# Configurações do servidor
server:
  port: 8080
  servlet:
    context-path: /

spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/postgres
    username: ${USERNAME_POSTGRES}
    password: ${PASSWORD_POSTGRES}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

# Configurações do logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG